language: csharp
mono: none
os:
 - linux
 - osx


matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: ELECTRONIZE_OS_NAME=linux
    - os: osx
      osx_image: xcode8.2
      env: ELECTRONIZE_OS_NAME=darwin
            
addons:
  apt:
    packages:
    - libunwind8
      

services:
 - docker


dotnet: 2.1.4    # this is SDK version. See https://github.com/dotnet/core/blob/master/release-notes/download-archive.md
solution: Papercut.sln
env:
 - CONFIGURATION=Release
  
  
install:
  - nvm install 8.6.0
  - nvm use 8.6.0
 
script:
 - cd $TRAVIS_BUILD_DIR ; dotnet restore -r $TRAVIS_OS_NAME-x64
 - cd $TRAVIS_BUILD_DIR/test/Papercut.WebUI.Tests ; dotnet test
 - cd $TRAVIS_BUILD_DIR/src/Papercut.Service ; dotnet publish -c $CONFIGURATION -r $TRAVIS_OS_NAME-x64 --self-contained
 
 - cd $TRAVIS_BUILD_DIR/src/Papercut.Desktop
 - npm install electron-packager --global ; dotnet electronize build $ELECTRONIZE_OS_NAME
 
 # Replease artifact to Release, 
 # Replace main.js to trigger administrative privileges if needed
 # Use Papercut as application name
 - dotnet publish -c $CONFIGURATION -r $TRAVIS_OS_NAME-x64 --output $TRAVIS_BUILD_DIR/src/Papercut.Desktop/obj/desktop/$ELECTRONIZE_OS_NAME/bin
 - cp -f $TRAVIS_BUILD_DIR/src/Papercut.Desktop/obj/desktop/$ELECTRONIZE_OS_NAME/bin/main.js $TRAVIS_BUILD_DIR/src/Papercut.Desktop/obj/desktop/$ELECTRONIZE_OS_NAME/main.js
 - cp -f $TRAVIS_BUILD_DIR/src/Papercut.Desktop/obj/desktop/$ELECTRONIZE_OS_NAME/bin/package.json $TRAVIS_BUILD_DIR/src/Papercut.Desktop/obj/desktop/$ELECTRONIZE_OS_NAME/package.json
 - cp -f $TRAVIS_BUILD_DIR/src/Papercut.Desktop/obj/desktop/$ELECTRONIZE_OS_NAME/bin/launch.sh $TRAVIS_BUILD_DIR/src/Papercut.Desktop/obj/desktop/$ELECTRONIZE_OS_NAME/launch.sh
 - cd $TRAVIS_BUILD_DIR/src/Papercut.Desktop/obj/desktop/$ELECTRONIZE_OS_NAME/
 - npm install
 - electron-packager $TRAVIS_BUILD_DIR/src/Papercut.Desktop/obj/desktop/$ELECTRONIZE_OS_NAME/ Papercut --platform=$ELECTRONIZE_OS_NAME --arch=x64 --out=$TRAVIS_BUILD_DIR/src/Papercut.Desktop/bin/desktop/ --overwrite --no-prune --icon=$TRAVIS_BUILD_DIR/src/Papercut.Desktop/icons/Papercut-icon.icns --app-copyright="ChangemakerStudios" --app-version="5.5.$TRAVIS_BUILD_NUMBER-netcore"
 
deploy:
 # Upload PapercutService
 - cd $TRAVIS_BUILD_DIR/src/Papercut.Service/bin/Release/netcoreapp2.0/$TRAVIS_OS_NAME-x64/publish/
 - zip -r ../PapercutService.zip ./*
 - dotnet $TRAVIS_BUILD_DIR/azcopy/azcopy.dll --source $TRAVIS_BUILD_DIR/src/Papercut.Service/bin/Release/netcoreapp2.0/$TRAVIS_OS_NAME-x64/PapercutService.zip --destination https://papercutartifacts.blob.core.windows.net/prereleases/$TRAVIS_OS_NAME/5.5.$TRAVIS_BUILD_NUMBER-netcore/PapercutService.$TRAVIS_OS_NAME.5.5.$TRAVIS_BUILD_NUMBER-netcore.zip  --dest-key $azblobcontainerkey
  
 # Upload PapercutDesktop
 - cd $TRAVIS_BUILD_DIR/src/Papercut.Desktop/bin/desktop/Papercut-$ELECTRONIZE_OS_NAME-x64/
 - zip -r ../PapercutDesktop.zip ./*
 - dotnet $TRAVIS_BUILD_DIR/azcopy/azcopy.dll --source $TRAVIS_BUILD_DIR/src/Papercut.Desktop/bin/desktop/PapercutDesktop.zip --destination https://papercutartifacts.blob.core.windows.net/prereleases/$TRAVIS_OS_NAME/5.5.$TRAVIS_BUILD_NUMBER-netcore/PapercutDesktop.$TRAVIS_OS_NAME.5.5.$TRAVIS_BUILD_NUMBER-netcore.zip  --dest-key $azblobcontainerkey

 # Papercut Service Docker Image
 - cd $TRAVIS_BUILD_DIR ; ./Docker/build.sh

 # todo: Build & pack plugins

cache: yarn