language: csharp
mono: none
dist: trusty
sudo: required
dotnet: 1.0.4    # this is SDK version
solution: Papercut.sln
env:
  - CONFIGURATION=Release
services:
  - docker

install:
  - nvm install 6.11.4
  - nvm use 6.11.4
script:
 - cd $TRAVIS_BUILD_DIR ; dotnet restore -r ubuntu.14.04-x64
 - cd $TRAVIS_BUILD_DIR/src/Papercut.Service ; dotnet publish -c $CONFIGURATION -r ubuntu.14.04-x64
 - cd $TRAVIS_BUILD_DIR/test/Papercut.WebUI.Tests ; dotnet test

after_success:
  # Papercut Service Docker Image
  - cd $TRAVIS_BUILD_DIR ; ./Docker/build.sh

  # todo: Build & pack plugins

cache: yarn