os: Visual Studio 2015

configuration: Release

before_build:
  - nuget restore

after_build:
  - 7z a Papercut.zip %APPVEYOR_BUILD_FOLDER%\src\Papercut.UI\bin\Release\Papercut.exe
  - 7z a Papercut.zip %APPVEYOR_BUILD_FOLDER%\src\Papercut.UI\bin\Release\Papercut.exe.*
  - 7z a Papercut.zip %APPVEYOR_BUILD_FOLDER%\src\Papercut.UI\bin\Release\Readme.eml
  - 7z a PapercutService.zip %APPVEYOR_BUILD_FOLDER%\src\Papercut.Service\bin\Release\Papercut.Service.*
  - 7z a PapercutService.zip %APPVEYOR_BUILD_FOLDER%\extras\Install-Papercut-Service.bat
  - 7z a PapercutService.zip %APPVEYOR_BUILD_FOLDER%\extras\Uninstall-Papercut-Service.bat

artifacts:
  - path: Papercut.zip
  - path: PapercutService.zip