os: Visual Studio 2017

version: 5.5.{build}-netcore

configuration: Release

install:
  - docker version
  - ps: Install-Product node 8

before_build:
  - appveyor-retry dotnet restore

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%\src\Papercut.Service
  - dotnet publish -c %CONFIGURATION% -r win10-x64 --self-contained
  
   
 # Replease artifact to Release, 
 # Replace main.js to trigger administrative privileges if needed
 # Use Papercut as application name
  - cd %APPVEYOR_BUILD_FOLDER%\src\Papercut.Desktop\
  - npm install electron-packager --global
  - dotnet electronize build win
  - dotnet publish -c %CONFIGURATION% -r win-x64 --output %APPVEYOR_BUILD_FOLDER%\src\Papercut.Desktop\obj\desktop\win\bin
  - copy /Y %APPVEYOR_BUILD_FOLDER%\src\Papercut.Desktop\obj\desktop\win\bin\main.js %APPVEYOR_BUILD_FOLDER%\src\Papercut.Desktop\obj\desktop\win\main.js
  - copy /Y %APPVEYOR_BUILD_FOLDER%\src\Papercut.Desktop\obj\desktop\win\bin\package.json %APPVEYOR_BUILD_FOLDER%\src\Papercut.Desktop\obj\desktop\win\package.json
  - copy /Y %APPVEYOR_BUILD_FOLDER%\src\Papercut.Desktop\obj\desktop\win\bin\launch.sh %APPVEYOR_BUILD_FOLDER%\src\Papercut.Desktop\obj\desktop\win\launch.sh
  - cd %APPVEYOR_BUILD_FOLDER%\src\Papercut.Desktop\obj\desktop\win\
  - npm install
  - cd %APPVEYOR_BUILD_FOLDER%\src\Papercut.Desktop\
  - electron-packager %APPVEYOR_BUILD_FOLDER%\src\Papercut.Desktop\obj\desktop\win\ Papercut --platform=win32 --arch=x64 --out=%APPVEYOR_BUILD_FOLDER%\src\Papercut.Desktop\bin\desktop\ --overwrite --no-prune --app-copyright="ChangemakerStudios" --app-version="%APPVEYOR_BUILD_VERSION%" --icon=%APPVEYOR_BUILD_FOLDER%\src\Papercut.Desktop\icons\Papercut-icon.ico  --win32metadata.ProductName="Papercut" --win32metadata.FileDescription="Papercut Simple Desktop SMTP Server" --win32metadata.CompanyName="ChangemakerStudios"
  
after_build:
  # Papercut Service
  - cd %APPVEYOR_BUILD_FOLDER%\src\Papercut.Service\bin\Release\netcoreapp2.0\win10-x64\publish\
  - 7z a PapercutService.win.%APPVEYOR_BUILD_VERSION%.zip -r *.*
  - appveyor PushArtifact PapercutService.win.%APPVEYOR_BUILD_VERSION%.zip
  # - dotnet %APPVEYOR_BUILD_FOLDER%\azcopy\azcopy.dll --source %APPVEYOR_BUILD_FOLDER%\src\Papercut.Service\bin\Release\netcoreapp2.0\win10-x64\publish\PapercutService.win.%APPVEYOR_BUILD_VERSION%.zip --destination https://papercutartifacts.blob.core.windows.net/prereleases/windows/%APPVEYOR_BUILD_VERSION%/PapercutService.win.%APPVEYOR_BUILD_VERSION%.zip --dest-key %azblobcontainerkey%
 
  # Papercut Desktop
  - cd %APPVEYOR_BUILD_FOLDER%\src\Papercut.Desktop\bin\desktop\Papercut-win32-x64
  - 7z a PapercutDesktop.win.%APPVEYOR_BUILD_VERSION%.zip -r *.*
  - appveyor PushArtifact PapercutDesktop.win.%APPVEYOR_BUILD_VERSION%.zip
 # - dotnet %APPVEYOR_BUILD_FOLDER%\azcopy\azcopy.dll --source %APPVEYOR_BUILD_FOLDER%\src\Papercut.Desktop\bin\desktop\Papercut-win32-x64\PapercutDesktop.win.%APPVEYOR_BUILD_VERSION%.zip --destination https://papercutartifacts.blob.core.windows.net/prereleases/windows/%APPVEYOR_BUILD_VERSION%/PapercutDesktop.win.%APPVEYOR_BUILD_VERSION%.zip  --dest-key %azblobcontainerkey%

  # Papercut Service Docker Image
  - cd %APPVEYOR_BUILD_FOLDER%
  - ps: .\Docker\build.ps1

  # todo: Build & pack plugins

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%\test\Papercut.WebUI.Tests
  - dotnet test

cache:
  - "%LOCALAPPDATA%/Yarn"