os: Visual Studio 2017

version: 5.1.{build}-netcore

configuration: Release

install:
  - docker version
  - ps: Install-Product node 6

before_build:
  - appveyor-retry dotnet restore

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%\src\Papercut.Service
  - dotnet publish -c %CONFIGURATION% -r win10-x64 --self-contained
  - yarn install
  - dotnet build -c %CONFIGURATION%

after_build:
  # Papercut Service
  - cd %APPVEYOR_BUILD_FOLDER%\src\Papercut.Service\bin\Release\netcoreapp1.1\win10-x64\publish\
  - 7z a PapercutService.%APPVEYOR_BUILD_VERSION%.zip *.*
  - appveyor PushArtifact PapercutService.%APPVEYOR_BUILD_VERSION%.zip

  # Papercut Service Docker Image
  - cd %APPVEYOR_BUILD_FOLDER%
  - ps: .\Docker\build.ps1

  # todo: Build & pack plugins

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%\test\Papercut.WebUI.Tests
  - dotnet test

cache:
 - "%LOCALAPPDATA%/Yarn"